on: [push]

jobs:
  download_data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # Enable pushing changes back to the repo
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run API Data Download Script
        run: python data/callAPI.py

      - name: Commit and Push Updated JSON File
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Check if the file has changes
          git add data/reports.json
          if ! git diff --cached --quiet; then
            git commit -m "Update API data reports.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
