name: Daily API Data Update

on:
  schedule:
    # This cron expression schedules the workflow to run once per day at 00:00 UTC.
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python Dependencies
        run: pip install requests

      - name: Run API Data Download Script
        run: python data/callAPI.py

      - name: Commit and Push Updated JSON File
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Pull remote changes and rebase your changes on top.
          git pull --rebase
          git add data/reports.json
          if ! git diff --cached --quiet; then
            git commit -m "Update reports.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
