on: [push]

jobs:
  download_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run API Data Download Script
        run: callAPI.py

      - name: Upload JSON file artifact
        uses: actions/upload-artifact@v4
        with:
          name: reports-json
          path: reports.json
